version: 1.0.{build}

image: 
  - Ubuntu
 
install:
  - sudo apt -y install lcov
  
before_build:
  - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON -DCPACK_GENERATOR="TGZ" -DCMAKE_BUILD_TYPE=Coverage
  
build_script:
  - cmake --build _build

  
after_build:
  - cd _build 
  - cpack -G "TGZ" 
  - cd ..
  - cmake --build _build --target package 

test_script:
  - cd _build
  - ./check -s -r compact
  - ./unit_tests 
